export enum NOTIFICATION_TYPES {
  TOKENS_SWAP = 'tokensSwap',
  CRYPTO_PURCHASE = 'CRYPTO_PURCHASE',
  FIAT_PURCHASE = 'fiatPurchase',
  CHAT = 'chat',
  CRYPTO_PURCHASE_REJECTED = 'cryptoPurchaseRejected',
  FIAT_PURCHASE_REJECTED = 'fiatPurchaseRejected',
  TOKENS_SWAP_REJECTED = 'tokensSwapRejected',
  NFT_PURCHASE_ACCEPTED = 'nftPurchaseAccepted',
  NFT_PURCHASE_REJECTED = 'nftPurchaseRejected',
  PACKAGE_SUBSCRIPTION = 'packageSubscription',
  LOAN_EXPIRY = 'loadExpiry',
  LOAN_DEDUCTION = 'loanDeduction',
  SUBSCRIPTION_RENEW = 'subscriptionRenew',
  SUBSCRIPTION_EXPIRED = 'subscriptionExpired',
  SUBSCRIPTION_CANCELLED = 'subscriptionCancelled',
  BALANCE_RECEIVED = 'balanceReceived',
  DIRECT_WIRE = 'directWire',
  USER_BLOCK = 'userBlock',
}
